kind: Deployment
apiVersion: apps/v1
metadata:
  name: bookingapi
spec:
  template:
    spec:
      containers:
        - name: api
          volumeMounts:
          - name: appsettings
            mountPath: /app/appsettings.json
            subPath: appsettings.json
          - name: certificates
            mountPath: /app/Certificates
            readOnly: true      
      volumes:
        - name: appsettings
          configMap:
            name: appsettings
        - name: certificates
          secret:
            secretName: certificates
        